name: Mayhem
on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    name: ${{ matrix.os }} shared=${{ matrix.shared }} ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        shared: [false]
        build_type: [Release]
        include:
        - os: ubuntu-latest
          triplet: x64-linux
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        file: mayhem/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: Start analysis
      uses: forallsecure/mcode-action@v1
      with:
        mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
        args: --image ${{ steps.meta.outputs.tags }} --cmd /out/zeek-dns-fuzzer --target
          zeek-dns-fuzzer --file mayhem/zeek-dns-fuzzer.mayhemfile
        sarif-output: sarif
    - name: Upload SARIF file(s)
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: sarif
